[tool.ruff]
# By default ruff also respect gitignore files
# Same as Black.
line-length = 88
indent-width = 4
target-version = "py311"

[tool.ruff.lint]
# Enable Pyflakes (`F`), pycodestyle (`E`, `W`), isort (`I`), pep8-naming (`N`), flake8-bugbear (`B`)
# T201: check for prints, C90: mccabe complexity
select = [
    "F",
    "E",
    "W",
    "I",
    "T201",
    "C90",
    "DTZ",
    "UP",
    "ASYNC",
    "S",
    "B",
    "A",
    "COM",
    "C4",
    "ISC",
    "ICN",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "SLF",
    "SLOT",
    "SIM",
    "TCH",
    "PTH",
    "RUF",
] # "B", "N" to add later
ignore = [
    "E203",
    "E266",
    "E501",
    "F403",
    "S104",
    "B008",
    "C401",
    "ISC001",
    "SIM102",
    "SIM105",
    "RUF012", # We may want to enable "Mutable class attributes should be annotated with `typing.ClassVar`"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []


[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 18.
max-complexity = 18

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

[tool.mypy]
python_version = "3.11"
plugins = ["pydantic.mypy"]
exclude = '''(?x)(
      .git
    | __pycache__
    | .pytest_cache
    | .venv
)'''
strict = true
disallow_any_generics = false
